### ISSUE TITLE
Variable declarations

### ISSUE THREAD

**Issue by bkmgit** [1Hyena/atomorph#1]
May wish to use u_int8_t instead of uint8_t in color.h to get code to compile with g++ or gcc compiler instead of clang.

**Comment by 1Hyena** [comment]
Thanks for the advice, but apparently `uint8_t` [is the standard](https://stackoverflow.com/questions/3103400/how-to-overcome-u-int8-t-vs-uint8-t-issue-efficiently). Tried compiling the lib on my Linux Mint and it compiled perfectly.
